### ISSUE TITLE
acts-as-taggable-on migration issue

### ISSUE THREAD

**Issue by nulty** [refinery/refinerycms-blog#373]
I'm updated from 2.0 and bundled refinerycms-blog 2.1.0 and I'm having a problem when creating a blog post.

```
Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 11
```

It seems that the newest version of acts-as-taggable that expects a taggings_count column on the tags table. It's a new migration in 3.1 this migrations hasn't been copied over to Refinery.

In the short term maybe you could put a restriction on the version in the gemspec?

```
# refinerycms-blog.gemspec
s.add_dependency    'acts-as-taggable-on', '< 3.1'
```

This works for me.

**Comment by cyzanfar** [comment]
Changed version and it worked for me:

```Ruby
gem 'acts-as-taggable-on', '~> 3.5'
```

**Comment by king8757** [comment]
Please help me solve the problem.
rbenv  2.5.1
gems 2.5.0
bundler 1.16.2


``
Caused by:
Mysql2::Error: Unknown column 'taggings_count' in 'field list'
/home/king8757/peatio/db/seeds.rb:21:in `<top (required)>'
/home/king8757/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/king8757/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
``

**Comment by parndt** [comment]
Which version of `acts-as-taggable-on` are you using in your `Gemfile.lock` @king8757 ?
